workflows:
  ios-workflow:
    name: iOS Loan Manager Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
      groups:
        # You'll create this group in Codemagic UI
        - app_store_credentials
      
      vars:
        BUNDLE_ID: "com.example.myApp"  # Match your iOS bundle identifier
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      
      ios_signing:
        distribution_type: app_store  # or: ad_hoc | development
        bundle_identifier: com.example.myApp
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: | 
          flutter pub get
      
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=1
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com  # Replace with your email
        notify:
          success: true
          failure: true

  # Optional: Android workflow
  android-workflow:
    name: Android Loan Manager Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      android_signing:
        - keystore_reference  # You'll set this up in Codemagic UI
    
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: | 
          flutter pub get
      
      - name: Build APK
        script: | 
          flutter build apk --release
    
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true